apiVersion: monitoring.mroque/v1alpha1
kind: Prometheus
metadata:
  name: best-prometheus-in-the-world
spec:
  version: 2.33.0
  scrape_configs:
    - job_name: k8s_pods,
      kubernetes_sd_configs:
        - role: pod

