apiVersion: monitoring.mroque/v1alpha1
kind: Prometheus
metadata:
  name: best-prometheus-in-the-world
spec:
  version: 2.33.0
  scrape_configs:
  - job_name: 'best-prometheus-operator'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name

